name: deploy operate_first_sre

# Only run this when the master branch changes
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy_environment
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          pip install -r courses/course-operate_first_intro/requirements.txt

      # Build the book
      - name: Build the book
        run: |
          jupyter-book build courses/course-operate_first_intro/

      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
          destination_dir: operate_first_sre/
